#first attempt

# def sort_by_length(array)
#   sized = array.group_by { |el| el.size }
#   sized.sort.map { |arr| arr[1] }.flatten
# end

# refactored solution
def sort_by_length(arr)
  arr.sort_by(&:length)
end

#sort_by sorts enum using a set of keys generated by mapping the values in enum throug the block